### ISSUE TITLE
Little issue on iPhone XR

### ISSUE THREAD

**Issue by muriloebsantos** [kkieffer/ALCameraViewController#4] opened 2020-05-11 23:38 UTC
Hi, first of all I want to thank you for your fork . I've been having problems with the original pod, and yours seems much more stable and functional.

My problem with yours is on iPhone XR. The "rotate picture" button in the right/top looks weird in my device. I can see my battery status in the background. The problem is reproducible on XR simulator. 

![bug iphone XR](https://i.imgur.com/TGszaYs.jpg)

**Comment by kkieffer** [comment] 2020-05-12 01:04
Thanks for finding this. I only tested on iPad and iPhone 8.  Looks like the button has some transparency to its background.  Should be easy enough to fix, I'll take a look.

**Comment by kkieffer** [comment] 2020-05-13 00:52
I can't reproduce this with an iPhone XR simulator.  I tried iOS 12.4 and 13.3.  Can you provide more details on your configuration? Are you using the pod? Here's what my simulator shows:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/33581862/81759300-54f99400-9492-11ea-8733-f2ac69d0870d.png">

**Comment by muriloebsantos** [comment] 2020-05-13 14:09
I will try to provide more details as soon as possible. Maybe I'm wrong about simulator.

**Comment by muriloebsantos** [comment] 2020-05-13 22:58
I was able te reproduce this with XR Simulator, iOS 12.0. But it's important to notice that the same bug happens in my physical device with iOS 13.3.1

![image](https://user-images.githubusercontent.com/21248661/81874130-9bfb8e00-9553-11ea-9963-8a50586217cf.png)

**Comment by kkieffer** [comment] 2020-05-14 14:50
This is quite strange because I cannot replicate it on the same simulator.  Can you describe more about how you are building - are you running the Example "ALCameraViewController" from a cloned download?  Or is this within your own project?  What is your Xcode version? 

Can you try other simulators?  Do you have other physical devices you can try?

**Comment by muriloebsantos** [comment] 2020-05-18 22:27
I'm running it inside my app. Xcode: Version 11.3.1 (11C505). 

No problems with iPad Pro simulator for example. I don't know what happened, but it's better now on my XR. Now the gray circle background is appearing. On XR simulator still has the bug. I think we might close this issue for now.

![Image](https://i.imgur.com/r6CF8fY.jpg)

**Comment by kkieffer** [comment] 2020-05-18 22:41
the original code I think was supposed to disable the status bar from showing on that view controller.  ok, I'll close it for now.

**Closed as completed by kkieffer** 2020-05-18 22:41 UTC
Labels: bug
